apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
   matchLabels:
     app: {{ .Values.labels.app }}
  template:
    metadata:
      name: nginx-pod
      namespace: nginx
      labels:
        app: {{ .Values.labels.app }}
    spec:
     containers:
       - name: {{ .Values.nameOverrideContainer }}
         image: {{ .Values.image.repository }}
         ports:
          -  containerPort: {{ .Values.containerPortValue }}

