apiVersion: v1
kind: Service
metadata:
  name: nginx-svc 
  namespace: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.containerPortValue }}
      targetPort: {{ .Values.containerPortValue }}
      nodePort: {{ .Values.service.NodePortValue }}

